apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit270rachanaservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cit270rachanaservice
  template:
    metadata:
      name: cit270rachanaservice
      labels: 
        app: cit270rachanaservice
    spec:
      containers:
      - name: cit270rachanaservice
        image: gcr.io/cit-270-kubernetes-379820/rachana-api
        volumeMounts:
        - name: ssl
          mountPath: "/etc/letsencrypt/live/rachanakumbhakar.cit270.com/"
        command: ["npm"]
        args: ["run","start"]
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret:
          secretName: rachanakumbhakar