apiVersion: apps/v1
kind: Deployment
metadata:
    name: cit270rachanaservice
spce:
 replicas: 1
 selector:
  matchLabels:
   app: cit270rachanaservice
 template:
  metadata:
   name: cit270rachanaservice
   labels: 
    app: cit270rachanaservice
spec:
 containers:
   - name: cit270rachanaservice
   image: cit-270-kubernetes-379820
   volumeMounts:
    - name: ss1
      mountPath: "/etc/letsencrypt/live.SSL"
    command: ["npm"]
    args: ["run","start"]
    resorces:
    requests:
     cpu: 0.125
     memory: 500Mi
   limits:
    cpu: 0.125
    memory: 600M1
  imagePullPolicy: Always
  volumes:
  - name: ss1
   secret:
    secretName: rachanacerts